build:
    environment:
        mongodb: '3.2'
        node: v9.2.0
    project_setup:
        before:
            -
                command: yarn start
                background: true
    tests:
        override:
            -
                command: 'yarn test'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'

filter:
    excluded_paths:
        - "coverage"
        - "dist"
        - "node_modules"
        - "tests"

checks:
    javascript:
        code_rating: true
        duplicate_code: true
