language: node_js

install:
  - npm install -g codecov

node_js:
  - "node"
  - "8"
  - "7"

services:
  - mongodb

sudo: false

git:
  submodules: false

before_script:
  - yarn

script:
  - yarn start &
  - yarn test && codecov
