version: "3"
services:
  db:
    image: mongo
    container_name: "mongodb"
    ports:
      - "27018:27018"
    command: mongod --port 27018 --bind_ip_all
  web:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: "backend"
    environment:
      DB_URL: 'mongodb://db:27018'
      NODE_ENV: "development"
      DBWEBB_PORT: "8080"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: "yarn serve"
