version: "3"
services:
  db:
    image: mongo
    container_name: "mongodb"
    ports:
      - "27017:27017"
  web:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: "backend"
    environment:
      DB_HOST: db
      NODE_ENV: "development"
      DBWEBB_PORT: "8080"
    volumes:
      - ./:/app/
      - /app/node_modules/
    ports:
      - "8080:8080"
    command: "yarn serve"
