version: "3"
services:
  db:
    image: mongo
    container_name: "mongodb"
    ports:
      - "27018:27018"
    command: mongod --port 27018 --bind_ip_all

  node7:
    image: "node:7"
    user: "node"
    working_dir: /home/node/app
    environment:
      DB_URL: 'mongodb://db:27018'
      NODE_ENV: "development"
      DBWEBB_PORT: "8080"
    volumes:
      - ./:/home/node/app
    ports:
      - "1337:8080"
    command: "yarn start"
  node8:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      DB_URL: 'mongodb://db:27018'
      NODE_ENV: "development"
      DBWEBB_PORT: "8080"
    volumes:
      - ./:/home/node/app
    ports:
      - "1338:8080"
    command: "yarn start"

  node9:
    image: "node:9"
    user: "node"
    working_dir: /home/node/app
    environment:
      DB_URL: 'mongodb://db:27018'
      NODE_ENV: "development"
      DBWEBB_PORT: "8080"
    volumes:
      - ./:/home/node/app
    ports:
      - "1339:8080"
    command: "yarn start"

  web:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: "backend"
    environment:
      DB_URL: 'mongodb://db:27018'
      NODE_ENV: "development"
      DBWEBB_PORT: "8080"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: "yarn serve"
